use crate::Slime;
use std::thread;
use std::time::Duration;

pub fn story_true_1(slime: &Slime) {
    println!("\n===============================");
    println!("(무사히 성에 도착하였습니다.)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(4));
    println!("슬라임: 나도 알아😡");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(4));
    println!("슬라임: 이 성은 뭔데 왜이렇게 커?");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("(성은 총 4층?으로 구성 되어있다.)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("슬라임 -> 속마음: 이쯤되면 제작자가 직접 해설 하는거 아니야?");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(4));
    println!("슬라임: 들어가자 일단");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(2));
    println!("(끼익)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(4));
    println!("(성에 들어서니 커다란 오크가 있었다.)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("슬라임: 나도 알아!!! 설마 때리는거 아니지?");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("오크: ???감히 마왕님에 성에 침입하다니... 용서 할 수 없다!");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("슬라임: 잠..잠깐 타임!");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("(그 순간 슬라임의 눈에 검과 방패가 보였다.)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("(슬라임은 검과 방패를 획득하였다!)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(4));
    println!("슬라임: 그게 중요한게 아니잖아! 저거 쓰러트릴 순 있어?");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("슬라임: 에라 모르겠다 도망ㄱ..? (문이 굳게 닫혔다.)");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("제작자: 👍");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(5));
    println!("슬라임: ^^ (난 행복해요)");
    thread::sleep(Duration::from_secs(2));
    println!("슬라임: 안 행복해!!!! 야!! 제작자!!!");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(4));
    println!("슬라임: 하... 어쩔수 없나...쓰러트리는 수 밖에");
    println!("\n===============================");
    thread::sleep(Duration::from_secs(3));
    println!("슬라임: 덤벼!");
}